name: meu_primeiro_app
description: "A new Flutter project."
publish_to: 'none' # Remove esta linha se quiser publicar na pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0
  flutter_native_splash: ^2.4.6
  supabase_flutter: ^2.9.1
  image_picker: ^1.1.2  # Use a versão mais recente disponível
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  image_cropper: ^9.1.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/fundo_estadio.png
    - assets/jogador_fundo.png
    - assets/tecnico_fundo.png
    - assets/torcedor_fundo.png
    - assets/escudo_sem_clube.png
    - assets/card_fifa.png
    - assets/default_avatar.png
    - assets/teste.png
    - assets/bandeiras/ale.png
    - assets/bandeiras/ago.png
    - assets/bandeiras/arg.png
    - assets/bandeiras/bol.png
    - assets/bandeiras/bra.png
    - assets/bandeiras/cpv.png
    - assets/bandeiras/chl.png
    - assets/bandeiras/chn.png
    - assets/bandeiras/col.png
    - assets/bandeiras/ecu.png
    - assets/bandeiras/esp.png
    - assets/bandeiras/eua.png
    - assets/bandeiras/fra.png
    - assets/bandeiras/hai.png
    - assets/bandeiras/nld.png
    - assets/bandeiras/ita.png
    - assets/bandeiras/jpn.png
    - assets/bandeiras/lbn.png
    - assets/bandeiras/moz.png
    - assets/bandeiras/pry.png
    - assets/bandeiras/per.png
    - assets/bandeiras/por.png
    - assets/bandeiras/gbr.png
    - assets/bandeiras/rus.png
    - assets/bandeiras/sui.png
    - assets/bandeiras/ukr.png
    - assets/bandeiras/uru.png
    - assets/bandeiras/ven.png
    - assets/estados/ac.png
    - assets/estados/al.png
    - assets/estados/ap.png
    - assets/estados/am.png
    - assets/estados/ba.png
    - assets/estados/ce.png
    - assets/estados/df.png
    - assets/estados/es.png
    - assets/estados/go.png
    - assets/estados/ma.png
    - assets/estados/mt.png
    - assets/estados/ms.png
    - assets/estados/mg.png
    - assets/estados/pa.png
    - assets/estados/pb.png
    - assets/estados/pr.png
    - assets/estados/pe.png
    - assets/estados/pi.png
    - assets/estados/rj.png
    - assets/estados/rn.png
    - assets/estados/rs.png
    - assets/estados/ro.png   
    - assets/estados/rr.png
    - assets/estados/sc.png
    - assets/estados/sp.png
    - assets/estados/se.png
    - assets/estados/to.png


flutter_native_splash:
  color: "#141A23"        # Cor de fundo (igual da sua logo, pode mudar!)
  image: assets/logo.png  # Caminho do seu logo principal do splash
  android: true
  ios: true
  web: false              # Splash nativo não aparece no web
  fullscreen: true

